"""create product table

Revision ID: 25_05_2025_04_06_01
Revises: 23_05_2025_11_53_47
Create Date: 2025-05-25 04:06:02.901173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25_05_2025_04_06_01'
down_revision: Union[str, None] = '23_05_2025_11_53_47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
