"""Add Seller Name to the product

Revision ID: f24ec08f3352
Revises: 25_05_2025_04_07_09
Create Date: 2025-05-28 20:07:36.964517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f24ec08f3352'
down_revision: Union[str, None] = '25_05_2025_04_07_09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('seller', sa.String(length=255)))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'seller')
    # ### end Alembic commands ###
